project:
  type: website

website:
  title: "IS415"
  navbar:
    left:
    - href: index.qmd
      text: Home
    - about.qmd
    - text: Hands-On
      menu:
        - text: "1"
          href: "Hands-On/1.html"
        - text: "2"
          href: "Hands-On/2.html"
        - text: "Chapter 4 & 5"
          href: "Hands-On/3.html"
    - text: In-Class
      menu: 
        - text: "1 "
          href: "inclass/ic1.html"
        - text: "2"
          href: "inclass/ic2.html"
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

