project:
  type: website

website:
  title: "IS415"
  navbar:
    left:
    - href: index.qmd
      text: Home
    - about.qmd
    - text: Hands-On
      menu:
        - text: "1"
          href: "Hands-On/1.html"
        - text: "2"
          href: "Hands-On/2.html"
        - text: "3"
          href: "Hands-On/3.html"
        - text: "5 (None in week 4)"
          href: "Hands-On/5.html"
        - text: "6"
          href: "Hands-On/6.html"
        - text: "12"
          href: "Hands-On/12.html"
    - text: In-Class
      menu: 
        - text: "1 "
          href: "inclass/ic1.html"
        - text: "2"
          href: "inclass/ic2.html"
        - text: "3"
          href: "inclass/ic3.html"
        - text: "4"
          href: "inclass/ic4.html"
        - text: "5"
          href: "inclass/ic5.html"
        - text: "6"
          href: "inclass/ic6.html"
        - text: "7"
          href: "inclass/ic7.html"
        - text: "Week 9"
          href: "inclass/ic9.html"
        - text: "Week 10"
          href: "inclass/ic10"
        - text: "Sick Week 11"
        - text: "Week 12"
          href: "inclass/ic12"
    - text: "Take Home 1"
      href: "take-home/th1.html"
    - text: "Take Home 3"
      href: "take-home/th3.html"
    - text: "Take Home 2"
      href: "take-home/th2.html"
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

