{
  "hash": "1520b78a01a6c566f815c4c64e31674b",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"In-class 4\"\nauthor: \"Lucas Vial\"\ndate: \"Sep 9 2024\"\ndate-modified: \"Date\"\nexecute: \n  eval: true\n  echo: true\n  freeze: true\n  warning: false\n---\n\n\n## Forest Fires in Sumatra, Indonesia \n\n### STKDE - Spatio-Temporal KDE (Kernel Density Estimator) \n\nKDE but you have one for distance in space and one in time\n\n### Imports and Data Wrangling \n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(sf, tmap, tidyverse, raster, spatstat, sparr, dplyr)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nkbb_sf <- st_read(dsn = \"data/4data/rawdata\", \n  layer = \"Kepulauan_Bangka_Belitung\") %>%\n  st_union() %>%\n  st_zm(drop = TRUE, what = \"ZM\") %>%\n  st_transform(crs = 32748) #This number is a EPSG \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `Kepulauan_Bangka_Belitung' from data source \n  `C:\\Users\\thevi\\OneDrive\\Desktop\\IS415\\IS415\\inclass\\data\\4data\\rawdata' \n  using driver `ESRI Shapefile'\nSimple feature collection with 298 features and 27 fields\nGeometry type: POLYGON\nDimension:     XYZ\nBounding box:  xmin: 105.1085 ymin: -3.116593 xmax: 106.8488 ymax: -1.501603\nz_range:       zmin: 0 zmax: 0\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n:::\n\n\nEPSG - A number to refer to an area on the (world) map\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkbb_owin <- as.owin(kbb_sf)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nclass(kbb_owin)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"owin\"\n```\n\n\n:::\n:::\n\n\nMake the csv (long, lat) into workable data :)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfire_sf <- read_csv(\"data/4data/rawdata/forestfires.csv\") %>%\n  st_as_sf(coords = c(\"longitude\", \"latitude\"),\n           crs = 4326) %>% \n  st_transform(crs = 32748)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nfire_sf <- fire_sf %>% \n  mutate(DayofYear = yday(acq_date)) %>%\n  mutate(Month_num = month(acq_date)) %>%\n  mutate(Month_fac = month(acq_date,\n                           label = TRUE,\n                           abbr = FALSE)) # January or JAN ??\n```\n:::\n\n\n\\^\\^ this code makes acq data numeric - makes them into new columns\n\n### Plotting\n\n**lubridate** is the timedate package used in this course (more talk about tidyverse 😻)\n\nBe aware of Interactive mode being on or off\n\nThe Below code is very literal - Its drawing the polygon of kbb_sf and then adding the dots over the top\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntm_shape(kbb_sf)+\n  tm_polygons() +\ntm_shape(fire_sf)+\n  tm_dots()\n```\n\n::: {.cell-output-display}\n![](ic4_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\nEach Month Plot\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntm_shape(kbb_sf)+\n  tm_polygons() +\ntm_shape(fire_sf)+\n  tm_dots(size = 0.1)+\ntm_facets(by=\"Month_fac\",\n          free.coords = FALSE, #will be weird and zoomed in\n          drop.units = TRUE)\n```\n\n::: {.cell-output-display}\n![](ic4_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Doesn't Work - \nfire_month <- fire_sf %>%\n  dplyr::select(Month_num)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nfire_month_ppp <- as.ppp(fire_month)\nfire_month_ppp\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMarked planar point pattern: 741 points\nmarks are numeric, of storage type  'double'\nwindow: rectangle = [521564.1, 695791] x [9658137, 9828767] units\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nfire_month_owin <- fire_month_ppp[kbb_owin]\n```\n:::\n\n\n### Computing and Plotting SPKDE\n\n\n::: {.cell}\n\n```{.r .cell-code}\nst_kde <- spattemp.density(fire_month_owin)\nsummary(st_kde)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSpatiotemporal Kernel Density Estimate\n\nBandwidths\n  h = 15102.47 (spatial)\n  lambda = 0.0304 (temporal)\n\nNo. of observations\n  741 \n\nSpatial bound\n  Type: polygonal\n  2D enclosure: [512066.8, 705559.4] x [9655398, 9834006]\n\nTemporal bound\n  [1, 12]\n\nEvaluation\n  128 x 128 x 12 trivariate lattice\n  Density range: [1.233458e-27, 8.202976e-10]\n```\n\n\n:::\n:::\n\n\nh = Spatial, which is 15102 = 15 km\n\nlambda = Temporal, which is 0.0304 = 0.03 months\n\nNotice how fig height and width makes the graphs looks half decent\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntims <- c(7,8,9,10,11,12)\npar(mfcol=c(2,3))\nfor(i in tims){\n  plot(st_kde, i,\n       override.par=FALSE,\n       fix.range=TRUE,\n       main=paste(\"KDE at month\",i))\n}\n```\n\n::: {.cell-output-display}\n![](ic4_files/figure-html/unnamed-chunk-13-1.png){width=1152}\n:::\n:::\n\n\nTheres a way to make it into a gif where you can do it day by day\n\n(he teased the code but didnt tell us how to do it 😠)\n",
    "supporting": [
      "ic4_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}